name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          ps -efwww
          kill $(ps aux | grep 'run.sh' | awk '{print $2}')
          kill $(ps aux | grep 'run-helper.sh' | awk '{print $2}')
          kill $(ps aux | grep 'Runner.Listener' | awk '{print $2}')
          sleep 5m
